backend:
  name: github
  repo: Hassan-Alam-Cloud/capstone-program-site
  branch: main
  oauth_endpoint: https://decap-cms-oauth.netlify.app/.netlify/functions/auth

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "updates"
    label: "Updates"
    folder: "src/content/updates"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
